session_name: xonotic-encoder-dev
windows:
- window_name: watchers
  layout: even-horizontal
  panes:
    - shell_command:
        - ./bin/watcher-records.sh
    - shell_command:
        - source activate
        - ./bin/watcher-youtube.sh
- window_name: develop
  layout: tiled
  panes:
    - shell_command:
        - vim -S ./config/develop.vim
