session_name: xonotic-records
windows:
- window_name: watchers
  layout: main-vertical
  panes:
    - shell_command:
        - ./bin/watcher-demos.sh
    - shell_command:
        - cd ~/0.8.1/Xonotic
        - ./xonotic-linux-dedicated.sh +serverconfig ctf.cfg
