session_name: xonotic-default
windows:
- window_name: watchers
  layout: tiled
  panes:
    - shell_command:
        - ./bin/watcher-demos.sh
    - shell_command:
        - ./bin/watcher-records.sh
    - shell_command:
        - ./bin/watcher-sliced.sh
    - shell_command:
        - source activate
        - ./bin/watcher-youtube.sh
    - shell_command:
        - cd ~/0.8.1/Xonotic
        - ./xonotic-linux-dedicated.sh +serverconfig ctf.cfg
