session_name: xonotic-encoder
windows:
- window_name: watchers
  layout: even-vertical
  panes:
    - shell_command:
        - ./bin/watcher-records.sh
    - shell_command:
        - ./bin/watcher-sliced.sh
    - shell_command:
        - source activate
        - ./bin/watcher-youtube.sh
